package org.emstrack.hospital.models;

/**
 * Created by mauricio on 2/5/18.
 * From autogenerated interface creted by
 * http://www.jsonschema2pojo.org/
 */

import java.util.List;

public class Profile {

    private List<AmbulancePermission> ambulances = null;
    private List<HospitalPermission> hospitals = null;

    public List<AmbulancePermission> getAmbulances() {
        return ambulances;
    }

    public void setAmbulances(List<AmbulancePermission> ambulances) {
        this.ambulances = ambulances;
    }

    public List<HospitalPermission> getHospitals() {
        return hospitals;
    }

    public void setHospitals(List<HospitalPermission> hospitals) {
        this.hospitals = hospitals;
    }

}