package org.emstrack.models;

/**
 * Created by mauricio on 2/5/18.
 * From autogenerated interface creted by
 * http://www.jsonschema2pojo.org/
 */

import java.util.List;

/**
 * A class representing a user profile.
 */
public class Profile {

    private List<AmbulancePermission> ambulances = null;
    private List<HospitalPermission> hospitals = null;

    public List<AmbulancePermission> getAmbulances() {
        return ambulances;
    }

    public void setAmbulances(List<AmbulancePermission> ambulances) {
        this.ambulances = ambulances;
    }

    public List<HospitalPermission> getHospitals() {
        return hospitals;
    }

    public void setHospitals(List<HospitalPermission> hospitals) {
        this.hospitals = hospitals;
    }

    public String toString() {
        String retval = "Profile with " + this.ambulances.size() + " ambulance(s) and " + this.hospitals.size() + " hospital(s)";
        for (AmbulancePermission ambulance: this.ambulances) {
            retval += "\n> Ambulance: " + ambulance.getAmbulanceIdentifier();
        }
        for (HospitalPermission hospital: this.hospitals) {
            retval += "\n> Hospital: " + hospital.getHospitalName();
        }
        return retval;
    }
}