package org.emstrack.models;

/**
 * Created by mauricio on 2/5/18.
 * From autogenerated interface creted by
 * http://www.jsonschema2pojo.org/
 */

import java.util.List;

public class Profile {

    private List<Ambulance> ambulances = null;
    private List<Hospital> hospitals = null;

    public List<Ambulance> getAmbulances() {
        return ambulances;
    }

    public void setAmbulances(List<Ambulance> ambulances) {
        this.ambulances = ambulances;
    }

    public List<Hospital> getHospitals() {
        return hospitals;
    }

    public void setHospitals(List<Hospital> hospitals) {
        this.hospitals = hospitals;
    }

    public String toString() {
        String retval = "Profile with " + this.ambulances.size() + " ambulance(s) and " + this.hospitals.size() + " hospital(s)";
        for (Ambulance ambulance: this.ambulances) {
            retval += "\n> AmbulanceData: " + ambulance.getAmbulanceIdentifier();
        }
        for (Hospital hospital: this.hospitals) {
            retval += "\n> Hospital: " + hospital.getHospitalName();
        }
        return retval;
    }
}